name: Build Arch repository

on:
  repository_dispatch:
    types: build-arch-repo
  push:
    branches:
      - master
  schedule:
    - cron: '0 2 * * *'

jobs:
  manage-repo:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build Arch repository
        uses: ./.github/actions/packages
      - name: Upload to server
        run: ./upload.sh
        env:
          WEBDAV_TOKEN: ${{ secrets.WEBDAV_TOKEN }}
          WEBDAV_URL: ${{ secrets.WEBDAV_URL }}