name: Build Arch repository

on:
  repository_dispatch:
    types: build-arch-repo
  push:
    branches:
      - master
  schedule:
    - cron: '0 2 * * *'

jobs:
  manage-repo:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build Arch repository
        uses: ./.github/actions/packages